name: firebase
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.34
  http: ^1.1.0
  path_provider: ^2.0.15
  path: ^1.8.3
  image_picker: ^1.0.2
  file_picker: ^6.1.1
  flutter_cache_manager: ^3.3.0
  connectivity_plus: ^4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/brain_icon.png