// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7zdhpOX6EWFcdv1rsHZw77ltKkXSzokU',
    appId: '1:374672873475:android:d5bbafd5ca666f00b49636',
    messagingSenderId: '374672873475',
    projectId: 'dementialink-15c06',
    databaseURL: 'https://dementialink-15c06-default-rtdb.firebaseio.com',
    storageBucket: 'dementialink-15c06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-fS_E7vcb7RZ2F5cfkq-ycwCJ-6c3dcM',
    appId: '1:374672873475:ios:27ddb78cbd52b579b49636',
    messagingSenderId: '374672873475',
    projectId: 'dementialink-15c06',
    databaseURL: 'https://dementialink-15c06-default-rtdb.firebaseio.com',
    storageBucket: 'dementialink-15c06.firebasestorage.app',
    androidClientId: '374672873475-5kd79vo4f3387ak5ia6t8auetin5gbsh.apps.googleusercontent.com',
    iosClientId: '374672873475-i3md383d9667a8q91kkongsrq5b630gm.apps.googleusercontent.com',
    iosBundleId: 'com.example.dementialinkfinale',
  );
}